version: '3'
services:
    reverse-proxy:
        container_name: reverse-proxy
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf

    server:
        container_name: server
        build: ./server
        environment:
            - PORT=3000
        expose:
            - "3000"


    client:
        container_name: client
        build: ./client
        expose:
            - "8080"